image:
  repository: traefik/whoami
  pullPolicy: IfNotPresent
  tag: latest

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 8080

workload:
  main:
    type: Job
    pod:
      containers:
        main:
          args:
            - --port
            - "8080"
          probes:
            liveness:
              enabled: true
              type: http
              port: "{{ .Values.service.main.ports.main.port }}"
            readiness:
              enabled: true
              type: http
              port: "{{ .Values.service.main.ports.main.port }}"
            startup:
              enabled: true
              type: http
              port: "{{ .Values.service.main.ports.main.port }}"
