# As we have by default enabled
# a "main" workload and service" for all charts
# We disable it so tests run with their defined
# values (Tests use a different named values)
workload:
  main:
    enabled: false

service:
  main:
    enabled: false
