image:
  repository: traefik/whoami
  pullPolicy: IfNotPresent
  tag: latest

service:
  main:
    ports:
      main:
        port: 8080

controllers:
  main:
    pod:
      containers:
        main:
          args:
            - --port
            - '8080'

          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true

rbac:
  main:
    enabled: true
    rules:
      - apiGroups:
          - ""
        resources:
          - services
          - endpoints
          - secrets
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - extensions
          - networking.k8s.io
        resources:
          - ingresses
          - ingressclasses
        verbs:
          - get
          - list
          - watch
      - apiGroups:
          - extensions
          - networking.k8s.io
        resources:
          - ingresses/status
        verbs:
          - update
      - apiGroups:
          - traefik.containo.us
        resources:
          - ingressroutes
          - ingressroutetcps
          - ingressrouteudps
          - middlewares
          - middlewaretcps
          - tlsoptions
          - tlsstores
          - traefikservices
          - serverstransports
        verbs:
          - get
          - list
          - watch

serviceAccount:
  main:
    create: true
