image:
  repository: traefik/whoami
  pullPolicy: IfNotPresent
  tag: latest

volumeClaimTemplates:
  test:
    mountPath: /test
    accessMode: "ReadWriteOnce"
    size: 1Gi

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 8080

controllers:
  main:
    type: StatefulSet
    replicas: 2
    pod:
      containers:
        main:
          args:
            - --port
            - "8080"

          probes:
            liveness:
              enabled: true
            readiness:
              enabled: true
            startup:
              enabled: true
